// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Henspe.iOS
{
	public partial class MainLocationRowViewCell : UITableViewCell
	{
		public UIKit.UIImageView ImgImage { get { return imgImage; } set { imgImage = value; } }
		public UIKit.UILabel LabLabelTop { get { return labLabelTop; } set { labLabelTop = value; } }
		public UIKit.UILabel LabLabelBottom { get { return labLabelBottom; } set { labLabelBottom = value; } }

		public MainLocationRowViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
