// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Henspe.iOS
{
	public partial class MainNormalRowViewCell : UITableViewCell
	{
		public UIKit.UIImageView ImgImage { get { return imgImage; } set { imgImage = value; } }
        public UIKit.UILabel LabLabel { get { return labLabel; } set { labLabel = value; } }
		public UIKit.UIView ViewImage { get { return viewImage; } set { viewImage = value; } }
        
		public MainNormalRowViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
