// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Henspe.iOS
{
	public partial class SettingsTopInfoTableCell : UITableViewCell
	{
        public UIKit.UILabel LabInfo { get { return labInfo; } set { labInfo = value; } }

        public SettingsTopInfoTableCell (IntPtr handle) : base (handle)
		{
		}
	}
}
