// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Henspe.iOS
{
	public partial class ButtonsCell : UITableViewCell
	{
		public ButtonsCell (IntPtr handle) : base (handle)
		{
		}

        internal void SetContent()
        {
            BackgroundColor = UIColor.Clear;
        }
    }
}
