// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Henspe.iOS.Const;
using Henspe.iOS.Util;
using UIKit;
using Xamarin.Essentials;

namespace Henspe.iOS
{
	public partial class ButtonsCell : UITableViewCell
	{
		public ButtonsCell (IntPtr handle) : base (handle)
		{
		}

        internal void SetContent()
        {
            BackgroundColor = UIColor.Clear;
            labLeft.TextColor = ColorConst.Blue;
            labMiddle.TextColor = ColorConst.Blue;
            labRight.TextColor = ColorConst.Blue;

            SVGUtil.LoadSVGToButton(btnLeftButton, "ic_btn_set_position.svg", "ic_btn_set_position_down.svg");
            SVGUtil.LoadSVGToButton(btnMiddleButton, "ic_btn_traffic.svg", "ic_btn_traffic_down.svg");
            SVGUtil.LoadSVGToButton(btnRightButton, "ic_btn_directions.svg", "ic_btn_directions_down.svg");
        }

        partial void RightButtonClicked(NSObject sender)
        {
            var location = new Location(47.645160, -122.1306032);
            var options = new MapsLaunchOptions { Name = "Microsoft Building 25",
                                                  MapDirectionsMode = MapDirectionsMode.Driving };

            Maps.OpenAsync(location, options);
        }
    }
}
