// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Henspe.Core.ViewModel;
using Henspe.iOS.Const;
using UIKit;

namespace Henspe.iOS
{
    public partial class CoordTypeViewController : UIViewController
	{
        private SettingsViewModel _viewmodel;

        public CoordTypeViewController (IntPtr handle) : base (handle)
		{
		}

        public void Init(SettingsViewModel viewModel)
        {
            _viewmodel = viewModel;
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            View.BackgroundColor = ColorConst.backgroundColor;
        }

        public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
        {
            base.PrepareForSegue(segue, sender);

            if (segue.Identifier == "CoordTypeEmbeddedSegue")
            {
                var controller = (CoordTypeEmbeddedController)segue.DestinationViewController;
                controller.Init(_viewmodel);
            }
        }
    }
}
