// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using Henspe.Core.ViewModel;
using Henspe.iOS.Const;
using UIKit;

namespace Henspe.iOS
{
	public partial class CoordTypeEmbeddedController : UITableViewController
	{
        private SettingsViewModel _viewmodel;

        public CoordTypeEmbeddedController (IntPtr handle) : base (handle)
		{
		}

        public void Init(SettingsViewModel viewModel)
        {
            _viewmodel = viewModel;
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            TableView.RowHeight = UITableView.AutomaticDimension;
            TableView.EstimatedRowHeight = 60;
            TableView.TableFooterView = new UIView(CGRect.Empty);
        }

        private void ApplyTheme()
        {
            View.BackgroundColor = ColorConst.backgroundColor;

            var headerFont = FontConst.fontHeading;
            var normalFont = FontConst.Medium;

            lblDDTitle.TextColor = ColorConst.textColor;
            lblDDTitle.Font = headerFont;

            lblDDSub1.TextColor = ColorConst.textColor;
            lblDDSub1.Font = normalFont;

            lblDDSub2.TextColor = ColorConst.textColor;
            lblDDSub2.Font = normalFont;

            lblDDMTitle.TextColor = ColorConst.textColor;
            lblDDMTitle.Font = headerFont;

            lblDDMSub1.TextColor = ColorConst.textColor;
            lblDDMSub1.Font = normalFont;

            lblDDMSub2.TextColor = ColorConst.textColor;
            lblDDMSub2.Font = normalFont;

            lblDMSTitle.TextColor = ColorConst.textColor;
            lblDMSTitle.Font = headerFont;

            lblDMSSub1.TextColor = ColorConst.textColor;
            lblDDMSub1.Font = normalFont;

            lblDMSSub2.TextColor = ColorConst.textColor;
            lblDDMSub2.Font = normalFont;

            lblUTMTitle.TextColor = ColorConst.textColor;
            lblUTMTitle.Font = headerFont;

            lblUTMSub1.TextColor = ColorConst.textColor;
            lblUTMSub1.Font = normalFont;

            lblUTMSub2.TextColor = ColorConst.textColor;
            lblUTMSub2.Font = normalFont;

            cellDD.BackgroundColor = UIColor.Clear;
            cellDDM.BackgroundColor = UIColor.Clear;
            cellDMS.BackgroundColor = UIColor.Clear;
            cellUTM.BackgroundColor = UIColor.Clear;
        }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            ApplyTheme();

            var rows = _viewmodel.CoordinateRows;

            var row = rows[0];
            lblDDTitle.Text = row.Title;
            lblDDSub1.Text = row.Sub1;
            lblDDSub2.Text = row.Sub2;

            row = rows[1];
            lblDDMTitle.Text = row.Title;
            lblDDMSub1.Text = row.Sub1;
            lblDDMSub2.Text = row.Sub2;

            row = rows[2];
            lblDMSTitle.Text = row.Title;
            lblDMSSub1.Text = row.Sub1;
            lblDMSSub2.Text = row.Sub2;

            row = rows[3];
            lblUTMTitle.Text = row.Title;
            lblUTMSub1.Text = row.Sub1;
            lblUTMSub2.Text = row.Sub2;

            TableView.SelectRow(NSIndexPath.FromRowSection(_viewmodel.SelectedCoordinatesRow, 0), false, UITableViewScrollPosition.None);
        }

        public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
        {
            _viewmodel.SaveCoordinatesFormat(_viewmodel.CoordinateRows[indexPath.Row].CoordinateFormat);
        }
    }
}
