// This file has been autogenerated from a class added in the UI designer.

using System;
using AVFoundation;
using AVKit;
using CoreAnimation;
using CoreGraphics;
using Foundation;
using Henspe.iOS.Const;
using Henspe.iOS.Util;
using UIKit;

namespace Henspe.iOS
{
	public partial class HelpUsViewController : UIViewController
	{
        private CAGradientLayer _gradient;
        private AVPlayer _player;
        private AVPlayerViewController _preview;

        public HelpUsViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            lblAboutHENSPE.TextColor = ColorConst.textColor;
            lblAboutSNLA.TextColor = ColorConst.textColor;
            lblYesPlease.TextColor = ColorConst.textColor;
            labShowMore.TextColor = ColorConst.textColor;

            btnSMS.BackgroundColor = ColorConst.Blue;
            btnEmail.BackgroundColor = ColorConst.Blue;
            btnNoThankYou.SetTitleColor(ColorConst.Blue, UIControlState.Normal);

            btnSMS.Layer.CornerRadius = 5;
            btnEmail.Layer.CornerRadius = 5;

            lblAboutHENSPE.Text = LangUtil.Get("HelpUs.AboutHENSPE");
            lblAboutSNLA.Text = LangUtil.Get("HelpUs.AboutSNLA");
            labShowMore.Text = LangUtil.Get("HelpUs.More");
            btnNoThankYou.SetTitle(LangUtil.Get("HelpUs.No"), UIControlState.Normal);
            btnSMS.SetTitle(LangUtil.Get("HelpUs.SMS"), UIControlState.Normal);
            btnEmail.SetTitle(LangUtil.Get("HelpUs.Email"), UIControlState.Normal);

            SetupScrollView();

            SetupVideo();

        }

        private void SetupScrollView()
        {
            SVGUtil.LoadSVGToImageView(imgArrow, "ic_arrow_up.svg", new System.Collections.Generic.Dictionary<string, string>());

            _gradient = new CAGradientLayer();
            _gradient.Frame = scrollViewAboutSNLA.Bounds;
            _gradient.Colors = new[] { ColorConst.textColor.CGColor, UIColor.Clear.CGColor };
            _gradient.Locations = new[] { new NSNumber(0.6f), new NSNumber(1) };
            scrollViewAboutSNLA.Layer.Mask = _gradient;
            scrollViewAboutSNLA.Scrolled += ScrollViewAboutSNLA_Scrolled;
        }

        private void SetupVideo()
        {
            var url = NSUrl.FromFilename("video10.mp4");
            _player = new AVPlayer(url);
            _preview = new AVPlayerViewController();
            _preview.Player = _player;
            viewMovieContainer.AddSubview(_preview.View);
            _preview.ShowsPlaybackControls = true;
        }

        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);

            _player.Play();
        }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            _preview.View.Frame = viewMovieContainer.Bounds;
        }

        public override void ViewDidLayoutSubviews()
        {
            base.ViewDidLayoutSubviews();

            UpdateGradient();
            //_preview.View.Frame = viewMovieContainer.Bounds;
        }

        void ScrollViewAboutSNLA_Scrolled(object sender, EventArgs e)
        {
            var scrollViewHeight = scrollViewAboutSNLA.Frame.Size.Height;
            var scrollContentSizeHeight = scrollViewAboutSNLA.ContentSize.Height;
            var scrollOffset = scrollViewAboutSNLA.ContentOffset.Y;

            if (scrollOffset + scrollViewHeight == scrollContentSizeHeight)
            {
                HideGradient();
            }
            else
            {
                UpdateGradient();
            }
        }

        private void UpdateGradient()
        {
            scrollViewAboutSNLA.Layer.Mask = _gradient;
            _gradient.Frame = new CGRect(0, scrollViewAboutSNLA.ContentOffset.Y, scrollViewAboutSNLA.Bounds.Width, scrollViewAboutSNLA.Bounds.Height);

        }

        private void HideGradient()
        {
            scrollViewAboutSNLA.Layer.Mask = null;
        }
    }
}
