// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Henspe.iOS
{
	public partial class SettingsShowPositionDuringCallTableCell : UITableViewCell
	{
		public SettingsShowPositionDuringCallTableCell (IntPtr handle) : base (handle)
		{
		}
	}
}
