// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using CoreLocation;
using Foundation;
using Henspe.Core.ViewModel;
using Henspe.iOS.Const;
using UIKit;

namespace Henspe.iOS
{
	public partial class SettingsViewController : UITableViewController
	{
        private SettingsViewModel _viewmodel;

        public SettingsViewController (IntPtr handle) : base (handle)
		{
            _viewmodel = new SettingsViewModel();
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            _viewmodel.Init();

            TableView.RowHeight = UITableView.AutomaticDimension;
            TableView.EstimatedRowHeight = 70;
            TableView.TableFooterView = new UIView(CGRect.Empty);

            ApplyTheme();
        }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            lblCoordValue.Text = _viewmodel.CoordinateTypeText;
            lblContactValue.Text = _viewmodel.ResponseText;

            //TODO: Find out how to localize this
            var text = string.Empty;
            if (CLLocationManager.Status == CLAuthorizationStatus.NotDetermined)
                text = "Ikke valgt";
            else if (CLLocationManager.Status == CLAuthorizationStatus.AuthorizedAlways)
                text = "Alltid";
            else if (CLLocationManager.Status == CLAuthorizationStatus.AuthorizedWhenInUse)
                text = "Når i bruk";
            else if (CLLocationManager.Status == CLAuthorizationStatus.Denied)
                text = "Aldri";
            lblPlaceValue.Text = text;
        }

        private void ApplyTheme()
        {
            View.BackgroundColor = ColorConst.backgroundColor;

            lblCoordDescription.TextColor = ColorConst.textColor;
            lblCoordDescription.Font = FontConst.Medium;

            lblCoordValue.TextColor = ColorConst.textColor;
            lblCoordValue.Font = FontConst.MediumRegular;

            lblContactDescription.TextColor = ColorConst.textColor;
            lblContactDescription.Font = FontConst.Medium;

            lblContactSubDescription.TextColor = ColorConst.textColor;
            lblContactSubDescription.Font = FontConst.MediumRegular;

            lblContactValue.TextColor = ColorConst.textColor;
            lblContactValue.Font = FontConst.MediumRegular;

            lblPlaceDescription.TextColor = ColorConst.textColor;
            lblPlaceDescription.Font = FontConst.Medium;

            lblPlaceSubDescription.TextColor = ColorConst.textColor;
            lblPlaceSubDescription.Font = FontConst.MediumRegular;

            lblPlaceValue.TextColor = ColorConst.textColor;
            lblPlaceValue.Font = FontConst.MediumRegular;

            lblTerms.TextColor = ColorConst.textColor;
            lblTerms.Font = FontConst.Medium;

            cellCoord.BackgroundColor = UIColor.Clear;
            cellPlace.BackgroundColor = UIColor.Clear;
            cellContact.BackgroundColor = UIColor.Clear;
            cellTerms.BackgroundColor = UIColor.Clear;
        }

        public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
        {
            base.PrepareForSegue(segue, sender);

            if(segue.Identifier == "SettingsCoordTypeSegue")
            {
                var controller = (CoordTypeViewController)segue.DestinationViewController;
                controller.Init(_viewmodel);
            }
        }

        public override NSIndexPath WillSelectRow(UITableView tableView, NSIndexPath indexPath)
        {
            if (indexPath.Section == 4)
                return null;
            return indexPath;
        }

        public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
        {
            if(indexPath.Section == 1)
                UIApplication.SharedApplication.OpenUrl(new NSUrl(UIApplication.OpenSettingsUrlString), new NSDictionary(), null);
        }

        public override void WillDisplayHeaderView(UITableView tableView, UIView headerView, nint section)
        {
            headerView.TintColor = ColorConst.headerBackgroundColor;
            var header = headerView as UITableViewHeaderFooterView;
            header.TextLabel.TextColor = ColorConst.largeTextColor;
            header.TextLabel.Font = FontConst.fontHeading;
        }

        public override nfloat GetHeightForHeader(UITableView tableView, nint section)
        {
            return 40;
        }
    }
}
